version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "20:00"
      timezone: "Asia/Tashkent"
    cooldown:
      default-days: 2
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "20:00"
      timezone: "Asia/Tashkent"
    cooldown:
      default-days: 2
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pre-commit
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "20:00"
      timezone: "Asia/Tashkent"
    cooldown:
      default-days: 2
    groups:
      pre-commit:
        patterns:
          - "*"
