services:
  release-bot:
    container_name: release-bot
    image: ghcr.io/janisv/release-bot:latest
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${}
      - GITHUB_TOKEN=<github_token>
      - SITE_URL=https://<your_domain_name> # optional
    ports:
      - 8000:8000
    volumes:
      - /path/to/data:/app/data
