"""Add starred field for user repo

Revision ID: 6c2a7c346237
Revises: 54cb934e3930
Create Date: 2025-12-12 11:41:52.623049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2a7c346237'
down_revision = '54cb934e3930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_repo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starred', sa.Boolean(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_repo', schema=None) as batch_op:
        batch_op.drop_column('starred')

    # ### end Alembic commands ###
