"""set chat.release_note_format to ReleaseFormat enum with ReleaseFormat.markdown default

Revision ID: 997ab6b455b5
Revises: 62a015d650b6
Create Date: 2026-08-22 02:35:47.905712

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "997ab6b455b5"
down_revision: str | Sequence[str] | None = "62a015d650b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat", "release_note_format", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat", "release_note_format", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
